version: '3.3'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik_platforms
    ports:
      - "8081:8081"
      - "8082:8082"
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=platforms
      - --entrypoints.platforms.address=:8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=platforms"
      - "traefik.http.routers.api.rule=Host(`monitor.dev.nos.to`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.platforms-shopware.entrypoints=platforms"
      - "traefik.http.routers.platforms-prestashop.entrypoints=platforms"
  shopware:
    hostname: shopware
    #docker build -t nosto-shopware . or it will try to pull from hub.docker
    image: nosto-shopware
#    build:
#      context: ./shopware
#      dockerfile: ./Dockerfile
    links:
      - mariadb
    #    ports:
    #      - 9004:9002  # Enable in order to use XDebug
    extra_hosts:
      - my.dev.nos.to:192.168.65.254
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shopware.rule=Host(`shopware.dev.nos.to`)"
      - "traefik.http.routers.shopware.entrypoints=platforms"
      - "traefik.http.services.shopware.loadbalancer.server.port=80"
    volumes:
      - type: bind
        source: ./shopware/nosto-shopware
        target: /var/www/html/shopware/Plugins/Community/Frontend/NostoTagging
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: shopware
      VIRTUAL_HOST: shopware.dev.nos.to:8081
      ADMIN_USER: admin
      ADMIN_PASSWORD: Admin12345
      # Use the env vars bellow to point to your local or staging play instance
      NOSTO_SERVER_URL: connect.my.dev.nos.to
      NOSTO_API_BASE_URL: http://host.docker.internal:9000/api
      NOSTO_OAUTH_BASE_URL: https://my.dev.nos.to/oauth
      NOSTO_WEB_HOOK_BASE_URL: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN_REGEXP: .*
      PHP_IDE_CONFIG: serverName=shopware.dev.nos.to:8081 # for XDebug
    depends_on:
      - traefik
  mariadb:
    build:
      context: ./mariadb
      dockerfile: ./Dockerfile
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data_platforms:/var/lib/mysql
    depends_on:
      - traefik
#    healthcheck:
#      test: /healthcheck.sh
#      interval: 2s
#      timeout: 2s
#      retries: 60
  prestashop:
    hostname: prestashop
    image: nosto-prestashop:1.7.8.10
    links:
      - mariadb
#    ports:
      # - 9003:9002  # Enable in order to use XDebug
    extra_hosts:
      - "my.dev.nos.to:192.168.65.254"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prestashop.rule=Host(`prestashop.dev.nos.to`)"
      - "traefik.http.routers.prestashop.entrypoints=platforms"
      - "traefik.http.services.prestashop.loadbalancer.server.port=80"
    volumes:
      - type: bind
        source: ./prestashop/nosto-prestashop
        target: /var/www/html/prestashop/modules/nostotagging
      - type: bind
        source: ./prestashop/nosto-prestashop-cron
        target: /var/www/html/prestashop/modules/mynostocron
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: prestashop
      VIRTUAL_HOST: prestashop.dev.nos.to:8081
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: Admin12345
      # Use the env vars bellow to point to your local or staging play instance
      NOSTO_SERVER_URL: connect.my.dev.nos.to
      NOSTO_API_BASE_URL: http://host.docker.internal:9000/api
      NOSTO_OAUTH_BASE_URL: https://my.dev.nos.to/oauth
      NOSTO_WEB_HOOK_BASE_URL: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN_REGEXP: .*
      PHP_IDE_CONFIG: serverName=prestashop.dev.nos.to:8081 # for XDebug
    depends_on:
      - traefik
  composer_sw:
    image: nosto/php-apache:7.4
    volumes:
      - type: bind
        source: ./shopware/nosto-shopware
        target: /var/www/html/shopware/Plugins/Community/Frontend/NostoTagging
    working_dir: /var/www/html/shopware/Plugins/Community/Frontend/NostoTagging
    depends_on:
      - shopware
    entrypoint:
      - bash
      - -e
      - -c
      - >
        case $$0 in
           install)
             composer "$$0" --no-interaction "$$@";
             ;;
           *)
             composer "$$0" "$$@"
             ;;
        esac;

  phan_sw:
    image: nosto/php-apache:7.4
    volumes:
      - type: bind
        source: ./shopware/nosto-shopware
        target: /var/www/html/shopware/modules/nostotagging
    working_dir: /var/www/html/shopware/modules/nostotagging
    depends_on:
      - shopware
    entrypoint:
      - bash
      - -e
      - -c
      - >
        ./vendor/bin/phan --config-file=phan.php --output-mode=checkstyle --output=chkphan.xml --processes=4
  phpmd_sw:
    image: nosto/php-apache:7.4
    volumes:
      - type: bind
        source: ./shopware/nosto-shopware
        target: /var/www/html/shopware/modules/nostotagging
    working_dir: /var/www/html/shopware/modules/nostotagging
    depends_on:
      - shopware
    entrypoint:
      - bash
      - -e
      - -c
      - >
        ./vendor/bin/phpmd . xml codesize,naming,unusedcode,controversial,design --exclude libs,var,build,tests,.phan --reportfile pmdphpmd.xml --ignore-violations-on-exit

  phpcs_sw:
    image: nosto/php-apache:7.4
    volumes:
      - type: bind
        source: ./shopware/nosto-shopware
        target: /var/www/html/shopware/modules/nostotagging
    working_dir: /var/www/html/shopware/modules/nostotagging
    depends_on:
      - shopware
    entrypoint:
      - bash
      - -e
      - -c
      - >
        ./vendor/bin/phpcs --standard=ruleset.xml --severity=10 --report=checkstyle --report-file=chkphpcs.xml .

  platforms:
    image: debian:stretch-slim
    depends_on:
      prestashop:
        condition: service_started
      shopware:
        condition: service_started
      traefik:
        condition: service_started
      mariadb:
        condition: service_started
    entrypoint:
      - /bin/true

#        condition: service_healthy
volumes:
  mariadb_data_platforms:
networks:
  platforms:
