services:
  ################################################
  ####          MariaDB Container          ######
  ##############################################
  db_ps:
    build:
      context: ../mariadb
      dockerfile: ./Dockerfile
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop

  ################################################
  ####        Prestashop Container         ######
  ##############################################
  prestashop:
    hostname: prestashop
    build:
      context: ./
      dockerfile: ./Dockerfile
#    image: nosto-prestashop:1.7.8.10
    links:
      - db_ps
    ports:
      - 8081:80
      # - 9003:9002  # Enable in order to use XDebug
    extra_hosts:
      - "my.dev.nos.to:192.168.65.254"
    volumes:
      - type: bind
        source: ./nosto-prestashop
        target: /var/www/html/prestashop/modules/nostotagging
#      - type: bind
#        source: ./nosto-prestashop-cron
#        target: /var/www/html/prestashop/modules/mynostocron
    environment:
      MYSQL_HOST: db_ps
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: prestashop
      VIRTUAL_HOST: prestashop.dev.nos.to:8081
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: Admin12345
      # Use the env vars bellow to point to your local or staging play instance
      NOSTO_SERVER_URL: connect.my.dev.nos.to
      NOSTO_API_BASE_URL: http://host.docker.internal:9000/api
      NOSTO_OAUTH_BASE_URL: https://my.dev.nos.to/oauth
      NOSTO_WEB_HOOK_BASE_URL: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN_REGEXP: .*
      PHP_IDE_CONFIG: serverName=prestashop.dev.nos.to:8081 # for XDebug

  composer: &composer
    image: nosto/php-apache:7.2
    volumes:
      - type: bind
        source: ./nosto-prestashop
        target: /var/www/html/prestashop/modules/nostotagging
    working_dir: /var/www/html/prestashop/modules/nostotagging
    entrypoint:
      - bash
      - -e
      - -c
      - >
        case $$0 in
           install)
             composer "$$0" --no-interaction "$$@";
             ;;
           *)
             composer "$$0" "$$@"
             ;;
        esac;

  phing:
    image: nosto/php-apache:7.2
    volumes:
      - type: bind
        source: ./nosto-prestashop
        target: /var/www/html/prestashop/modules/nostotagging
    working_dir: /var/www/html/prestashop/modules/nostotagging
    entrypoint:
      - bash
      - -e
      - -c
      - >
        ./libs/bin/phing -verbose -Dversion="$$0" -DcomposerDir=/root/.composer

  # phan:
  #   image: nosto/php-apache:7.2
  #   volumes:
  #     - type: bind
  #       source: ./nosto-prestashop
  #       target: /var/www/html/prestashop/modules/nostotagging
  #   working_dir: /var/www/html/prestashop/modules/nostotagging
  #   entrypoint:
  #     - bash
  #     - -e
  #     - -c
  #     - >
  #       ./libs/bin/phan --config-file=phan.php
  # phpmd:
  #   image: nosto/php-apache:7.2
  #   volumes:
  #     - type: bind
  #       source: ./nosto-prestashop
  #       target: /var/www/html/prestashop/modules/nostotagging
  #   working_dir: /var/www/html/prestashop/modules/nostotagging
  #   entrypoint:
  #     - bash
  #     - -e
  #     - -c
  #     - >
  #       ./libs/bin/phpmd . xml codesize,naming,unusedcode,controversial,design --exclude libs,var,build,tests,.phan --ignore-violations-on-exit

  # phpcs:
  #   image: nosto/php-apache:7.2
  #   volumes:
  #     - type: bind
  #       source: ./nosto-prestashop
  #       target: /var/www/html/prestashop/modules/nostotagging
  #   working_dir: /var/www/html/prestashop/modules/nostotagging
  #   entrypoint:
  #     - bash
  #     - -e
  #     - -c
  #     - >
  #       ./libs/bin/phpcs --standard=ruleset.xml --severity=10 .


##  You can fill the tokens here from your local playcart instance,
##  so you don't have to reconnect everytime you destroy the containers or some docker networking issues with the iframe
##  @TODO: move to .env and use a var here

# bin/console doctrine:query:sql '
#   INSERT INTO ps_configuration (id_shop_group, id_shop, name, value, date_add, date_upd) VALUES
#   (NULL, NULL, "NOSTOTAGGING_ACCOUNT_NAME", NULL, "2018-10-02 15:48:44", "2018-10-02 15:48:44");
#   SET @LAST_ID:=LAST_INSERT_ID();
#   INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) VALUES
#   (@LAST_ID, 1, "", "2018-10-02 15:48:44");
#
#   INSERT INTO ps_configuration (id_shop_group, id_shop, name, value, date_add, date_upd) VALUES
#   (NULL, NULL, "NOSTOTAGGING_API_TOKEN_SSO", NULL, "2018-10-02 15:48:44", "2018-10-02 15:48:44");
#   SET @LAST_ID:=LAST_INSERT_ID();
#   INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) VALUES
#   (@LAST_ID, 1, "", "2018-10-02 15:48:44");
#
#   INSERT INTO ps_configuration (id_shop_group, id_shop, name, value, date_add, date_upd) VALUES
#   (NULL, NULL, "NOSTOTAGGING_API_TOKEN_PRODUCTS", NULL, "2018-10-02 15:48:44", "2018-10-02 15:48:44");
#   SET @LAST_ID:=LAST_INSERT_ID();
#   INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) VALUES
#   (@LAST_ID, 1, "", "2018-10-02 15:48:44");
#
#   INSERT INTO ps_configuration (id_shop_group, id_shop, name, value, date_add, date_upd) VALUES
#   (NULL, NULL, "NOSTOTAGGING_API_TOKEN_RATES", NULL, "2018-10-02 15:48:44", "2018-10-02 15:48:44");
#   SET @LAST_ID:=LAST_INSERT_ID();
#   INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) VALUES
#   (@LAST_ID, 1, "", "2018-10-02 15:48:44");
#
#   INSERT INTO ps_configuration (id_shop_group, id_shop, name, value, date_add, date_upd) VALUES
#   (NULL, NULL, "NOSTOTAGGING_API_TOKEN_SETTINGS", NULL, "2018-10-02 15:48:44", "2018-10-02 15:48:44");
#   SET @LAST_ID:=LAST_INSERT_ID();
#   INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) VALUES
#   (@LAST_ID, 1, "", "2018-10-02 15:48:44");
#
#   INSERT INTO ps_configuration (id_shop_group, id_shop, name, value, date_add, date_upd) VALUES
#   (NULL, NULL, "NOSTOTAGGING_API_TOKEN_EMAIL", NULL, "2018-10-02 15:48:44", "2018-10-02 15:48:44");
#   SET @LAST_ID:=LAST_INSERT_ID();
#   INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) VALUES
#   (@LAST_ID, 1, "", "2018-10-02 15:48:44");
#
#   INSERT INTO ps_configuration (id_shop_group, id_shop, name, value, date_add, date_upd) VALUES
#   (NULL, NULL, "NOSTOTAGGING_API_TOKEN_APPS", NULL, "2018-10-02 15:48:44", "2018-10-02 15:48:44");
#   SET @LAST_ID:=LAST_INSERT_ID();
#   INSERT INTO ps_configuration_lang (id_configuration, id_lang, value, date_upd) VALUES
#   (@LAST_ID, 1, "", "2018-10-02 15:48:44")'


# networks:
#   default:
#     external:
#       name: platforms
