version: '3.3'

services:
  ################################################
  ####          MariaDB Container         ######
  ##############################################
  db_ps:
    image: nosto/mariadb:10.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    networks:
      - backend

  ################################################
  ####        Prestashop Container         ######
  ##############################################
  prestashop:
    build:
      context: ./
      dockerfile: ./Dockerfile
    links:
      - db_ps
    ports:
      - 80:80
      # - 9002:9002 #XDebug
    extra_hosts:
      my.dev.nos.to: 192.168.65.2
    networks:
      - web
      - backend
    volumes:
      - type: bind
        source: ./nosto-prestashop
        target: /var/www/html/prestashop/modules/nostotagging
    environment:
      MYSQL_HOST: db_ps
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: prestashop
      VIRTUAL_HOST: prestashop.dev.nos.to
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: Admin12345
      # Use the env vars bellow to point to your local or staging play instance
      NOSTO_SERVER_URL: connect.my.dev.nos.to
      NOSTO_API_BASE_URL: http://host.docker.internal:9000/api
      NOSTO_OAUTH_BASE_URL: https://my.dev.nos.to/oauth
      NOSTO_WEB_HOOK_BASE_URL: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN_REGEXP: .*
      PHP_IDE_CONFIG: serverName=prestashop.dev.nos.to # for XDebug

networks:
  web:
    external: true
  backend:
    external: false