services:
  ################################################
  ####          MariaDB Container          ######
  ##############################################
  db_sw:
    build:
      context: ../mariadb
      dockerfile: ./Dockerfile
#    ports:
#      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware

  ################################################
  ####        Shopware Container         ######
  ##############################################
  shopware:
    hostname: shopware
    build:
      context: ./
      dockerfile: ./Dockerfile
    links:
      - db_sw
    ports:
      - 9004:9002  # Enable in order to use XDebug
      - 8081:80
    extra_hosts:
      - my.dev.nos.to:192.168.65.254
    volumes:
      - type: bind
        source: ./nosto-shopware
        target: /var/www/html/shopware/Plugins/Community/Frontend/NostoTagging
    environment:
      MYSQL_HOST: db_sw
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: shopware
      VIRTUAL_HOST: shopware.dev.nos.to:8081
      ADMIN_USER: admin
      ADMIN_PASSWORD: Admin12345
      # Use the env vars bellow to point to your local or staging play instance
      NOSTO_SERVER_URL: connect.my.dev.nos.to
      NOSTO_API_BASE_URL: http://host.docker.internal:9000/api
      NOSTO_OAUTH_BASE_URL: https://my.dev.nos.to/oauth
      NOSTO_WEB_HOOK_BASE_URL: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN: https://my.dev.nos.to
      NOSTO_IFRAME_ORIGIN_REGEXP: .*
      PHP_IDE_CONFIG: serverName=shopware.dev.nos.to:8081 # for XDebug
  
  composer:
    image: nosto/php-apache:7.4
    volumes:
      - type: bind
        source: ./nosto-shopware
        target: /var/www/html/shopware/Plugins/Community/Frontend/NostoTagging
    working_dir: /var/www/html/shopware/Plugins/Community/Frontend/NostoTagging
    entrypoint:
      - bash
      - -e
      - -c
      - >
        case $$0 in
           install)
             composer "$$0" --no-interaction "$$@";
             ;;
           *)
             composer "$$0" "$$@"
             ;;
        esac;

  phan:
    image: nosto/php-apache:7.4
    volumes:
      - type: bind
        source: ./nosto-shopware
        target: /var/www/html/shopware/modules/nostotagging
    working_dir: /var/www/html/shopware/modules/nostotagging
    entrypoint:
      - bash
      - -e
      - -c
      - >
        ./vendor/bin/phan --config-file=phan.php --processes=4
  phpmd:
    image: nosto/php-apache:7.4
    volumes:
      - type: bind
        source: ./nosto-shopware
        target: /var/www/html/shopware/modules/nostotagging
    working_dir: /var/www/html/shopware/modules/nostotagging
    entrypoint:
      - bash
      - -e
      - -c
      - >
        ./vendor/bin/phpmd . xml codesize,naming,unusedcode,controversial,design --exclude libs,var,build,tests,.phan --reportfile pmdphpmd.xml --ignore-violations-on-exit
  phing:
    image: nosto/php-apache:7.4
    volumes:
      - type: bind
        source: ./nosto-shopware
        target: /var/www/html/shopware/modules/nostotagging
    working_dir: /var/www/html/shopware/modules/nostotagging
    entrypoint:
      - bash
      - -e
      - -c
      - >
        composer install && ./vendor/bin/phing -verbose -Dversion="$$0" -DcomposerDir=/root/.composer
  phpcs:
    image: nosto/php-apache:7.4
    volumes:
      - type: bind
        source: ./nosto-shopware
        target: /var/www/html/shopware/modules/nostotagging
    working_dir: /var/www/html/shopware/modules/nostotagging
    entrypoint:
      - bash
      - -e
      - -c
      - >
        ./vendor/bin/phpcs --standard=ruleset.xml --severity=10 .
